# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 夜行书生
subtitle: "临渊羡鱼，不如退而结网。" #副标题
description: "为众人抱薪者，不可使其冻毙于风雪。"#侧边栏的描述
keywords: [个人博客, 博客网站]
author: 夜行书生 #网站底部的By 夜行书生
#language: zh #侧边栏显示英文：You've read 100%
language: zh-Hans #侧边栏显示中文：你已经读了 100%
timezone:

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://yexingshusheng.com
#url: https://xgyxss.github.io
#permalink: :year/:month/:day/:title/
#permalink: :title.html #结合下面的lang，可用于制作多语言站点;后因SEO优化，减少了层级
permalink: :year/:month/:title.html
permalink_defaults:
  #lang: zh
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

permalink_pinyin:
  enable: true
  separator: '-'  # default: '-'

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: melody

# algolia
# 1.这个用不了
# npm install --save hexo-algolia
# https://github.com/thom4parisot/hexo-algolia
# https://www.npmjs.com/package/hexo-algolia#public-facing-search-options
# applicationID
# 不含field

# 2.
# npm install hexo-algoliasearch --save
# https://github.com/LouisBarranqueiro/hexo-algoliasearch
# appId
# 含field

algolia:
  appId: 'QOO2KQWBJ0'
  apiKey: '993ede762c7225acd4669201a2ab1dca'
  adminApiKey: '4fc5014f14a7bc684b174693194017af'
  chunkSize: 5000
  indexName: 'hexo'
  fields:
   - content:strip:truncate,0,500
   - excerpt:strip
   - gallery
   - permalink
   - photos
   - slug
   - tags
   - title

# npm install hexo-generator-feed
Plugins:
  - hexo-generate-feed
  - hexo-algoliasearch

# npm install hexo-generator-search --save
search:
  path: search.xml
  field: post
  content: true

# generate sitemap
# npm install hexo-generator-sitemap --save
# npm install hexo-generator-baidu-sitemap --save
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: git@github.com:xgyxss/xgyxss.github.io.git
  branch: main
